serverAddr = "frp.freefrp.net"
serverPort = 7000
auth.method = "token"
auth.token = "freefrp.net"

log.to = "/share/frpc.log"
log.level = "trace"
log.maxDays = 3

[[proxies]]
name = "your_proxy_name"
type = "http"
customDomains = ["your_domain"]
localPort = 8123
localIP = "0.0.0.0"

